
#
# This LookML file was generated by AtScale on 2026-07-28T11:41:50.270478843Z
#
# AtScale version: 2026.6.0
# Catalog: connected_fitness_subscription_lifecycle_catalog_main

connection: "cfsl_con"
label: "connected_fitness_subscription_lifecycle_catalog_main"


include: "/views/connected_fitness_subscription_lifecycle_catalog_main/connected_fitness_subscription_lifecycle.view.lkml"


explore: connected_fitness_subscription_lifecycle {
  label: "connected_fitness_subscription_lifecycle"
}

